version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: user
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db_data:/var/lib/postgresql/data  // Persist data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db_data:
    driver: local
